version: "3"
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: dbpassword_for_user
            MYSQL_DATABASE: eval_server_development
            MYSQL_USER: db_username
            MYSQL_PASSWORD: dbpassword_for_user
        restart: always
    web:
        build: .
        env_file: env
        command: "./bin/wait-for-it.sh db:3306 -s -t 30 -- ./bin/docker_start"
        volumes:
        - ./:/usr/src/app
        ports:
            - "8081:8081" 
        depends_on:
            - db
volumes:
  bundle:
    driver: local